trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Npm@1
  name: "install"
  inputs:
    command: 'custom'
    workingDir: 'client-app'
    customCommand: 'install --legacy-peer-deps'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- task: Npm@1
  name: "build"
  inputs:
    command: 'custom'
    workingDir: 'client-app'
    customCommand: 'run build'
